name: Metrics

on:
  schedule: [{cron: "0 5 */1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.README_TOKEN }}

          #options
          user: mpslanker
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: US/Denver
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes